# Generated by Django 3.2 on 2021-04-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210411_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_registered_with_this_app',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
